name: Test Config

on:
  pull_request:
    branches: 
    - 'release/**'
  workflow_dispatch:
jobs:
  config-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Config
        run: echo "Testing Config"
