name: Build Config

on:
  push:
    branches: 
    - 'release/**'

jobs:
  config-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Config
        run: echo "Building Config"
