name: Deploy

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
      version:
        description: 'Version'
        required: true
        default: latest
      environment:
        description: 'Environment'
        required: true
        options:
        - dev
        - test
        - prod 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploying ${{ github.event.inputs.environment }}, version: ${{ github.event.inputs.version }}'
        run: echo "Deploying ${{ github.event.inputs.environment }} / ${{ github.event.inputs.version }}"
