name: Deploy dev

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
      version:
        description: 'Version'
        required: true
        default: latest
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: 'Deploying prod, version: ${{ github.event.inputs.version }}'
        run: echo "Deploying prod/ ${{ github.event.inputs.version }}"
