name: Build Image

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
      version:
        description: 'Version'
        required: true
        default: latest
      environment:
        description: 'Environment'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploying Image for ${{ github.event.inputs.environment }}, version: ${{ github.event.inputs.version }}'
        run: 'echo "Deploying Image for ${{ github.event.inputs.environment }} / ${{ github.event.inputs.version }}'
