name: Build Image

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
      version:
        description: 'Config Version'
        required: true
        default: latest
      environment:
        description: 'Environment'
        required: true  
        options:
        - dev
        - test
        - prod 
      
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Image for ${{ github.event.inputs.environment }}
        run: echo "Building Image for ${{ github.event.inputs.environment }}"
